---
title: "Data analysis for the paper on omnivorism"
author: "Samuel Coavoux"
output: 
  html_document: 
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(message = FALSE,
               error = FALSE,
               echo = FALSE,
               warning = FALSE,
               results = 'asis',
               fig.path = "plot/",
               dpi = 1200)
```

```{r packages}
library(tidyverse)
library(lubridate)
library(here)
library(forcats)
library(janitor)
library(stargazer)
library(lme4)
library(effsize)
library(MuMIn)

loadRData <- function(fileName){
#loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}

```

```{r data}
load(here("data", "streams.RData"))
load(here("data", "french_users.RData"))
# Souci avec le suivant
# source(here("recodages", "in_english.R"))
source(here("recodages", "herfindhal_diversity.R"))
```

```{r misc_options}
if(isTRUE(getOption('knitr.in.progress'))) {
    output_type <- "html"#
} else {
    output_type <- "text"
}

theme_set(theme_bw(base_size = 12))

knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=" ")
})
options(scipen = 99)

```


We work on the usd database = users with herfindhal diversity. See scripts for details about their computation. Basically, inverse herfindhal, standardized (difference from a random walk) + logged for artist diversity, square rooted for genre diversity

```{r , fig.cap="Raw diversity"}
select(usd, starts_with("div_")) %>% pivot_longer(everything(), names_to = "names", values_to = "values") %>% 
  ggplot(aes(values)) +
  geom_histogram() +
  facet_wrap(~names, scales = "free", ncol = 5)
```

```{r , fig.cap="Theoretical diversity (random)"}
select(usd, starts_with("divstd_")) %>% pivot_longer(everything(), names_to = "names", values_to = "values") %>% 
  ggplot(aes(values)) +
  geom_histogram() +
  facet_wrap(~names, scales = "free", ncol = 3)
```

```{r , fig.cap="Standardized diversity"}
select(usd, starts_with("stddiv_")) %>% pivot_longer(everything(), names_to = "names", values_to = "values") %>% 
  ggplot(aes(values)) +
  geom_histogram() +
  facet_wrap(~names, scales = "free", ncol = 3)
```

```{r , fig.cap="Standardized diversity"}
select(usd, starts_with("stddiv_"), -stddiv_artists, -stddiv_genre, -stddiv_omni) %>%
  pivot_longer(everything(), names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "stddiv_")) %>% 
  separate(names, into = c("type", "guid"), sep = "_") %>% 
  ggplot(aes(values, fill = guid)) +
    geom_density(alpha = 0.5) +
    facet_wrap(~type)
    
```

# Bivariate

```{r}
ggplot(usd, aes(stddiv_artists_rec, stddiv_artists_stock)) +
  geom_point()
```

```{r}
ggplot(usd, aes(stddiv_genre_rec, stddiv_genre_stock)) +
  geom_point()
```

```{r}
ggplot(usd, aes(stddiv_omni_rec, stddiv_omni_stock)) +
  geom_point()
```


# Fixed effects models

```{r}
x <- select(usd, user_id, stddiv_artists_rec, stddiv_artists_stock, nb_guid, nb_stock, fq)
x <- pivot_longer(x, cols = starts_with("stddiv_artists")) %>% 
  mutate(name = str_extract(name, "(rec|stock)$") %>% factor(levels = c("stock", "rec")), 
         nb = ifelse(name == "rec", nb_guid, nb_stock)) %>% 
  select(-nb_guid, -nb_stock) %>% 
  group_by(user_id) %>% 
  filter(!any(is.na(value)))

fe_lm_artdiv <- lmer(value ~ I(log(nb/1000)) + (1 | user_id) + name, data = x)
```

```{r}
r.squaredGLMM(fe_lm_artdiv) %>% kable(caption = "Pseudo R2 modele diversité artiste")
```

```{r}
x <- select(usd, user_id, stddiv_genre_rec, stddiv_genre_stock, nb_guid, nb_stock, fq)
x <- pivot_longer(x, cols = starts_with("stddiv_")) %>% 
  mutate(name = str_extract(name, "(rec|stock)$") %>% factor(levels = c("stock", "rec")), 
         nb = ifelse(name == "rec", nb_guid, nb_stock)) %>% 
  select(-nb_guid, -nb_stock) %>% 
  group_by(user_id) %>% 
  filter(!any(is.na(value)))

fe_lm_genrediv <- lmer(value ~ I(log(nb/1000)) + (1 | user_id) + name, data = x)
```

```{r}
r.squaredGLMM(fe_lm_genrediv) %>% kable(caption = "Pseudo R2 modele diversité genre")
```


```{r}
x <- select(usd, user_id, stddiv_omni_rec, stddiv_omni_stock, nb_guid, nb_stock, fq)
x <- pivot_longer(x, cols = starts_with("stddiv_")) %>% 
  mutate(name = str_extract(name, "(rec|stock)$") %>% factor(levels = c("stock", "rec")), 
         nb = ifelse(name == "rec", nb_guid, nb_stock)) %>%   select(-nb_guid, -nb_stock) %>% 
  group_by(user_id) %>% 
  filter(!any(is.na(value)))

fe_lm_omnidiv <- lmer(value ~ I(log(nb/1000)) + (1 | user_id) + name, data = x)
```

```{r}
r.squaredGLMM(fe_lm_omnidiv) %>% kable(caption = "Pseudo R2 modele diversité omni")
```

```{r}
stargazer(fe_lm_artdiv, type = output_type)
stargazer(fe_lm_genrediv, type = output_type)
stargazer(fe_lm_omnidiv, type = output_type)
stargazer(fe_lm_artdiv, fe_lm_genrediv, fe_lm_omnidiv, 
          covariate.labels = c("Log(nb ecoutes / 1000)",
                               "Recommended",
                               "Constant"),
          dep.var.labels = c("Log std art div", "Genre div", "Omni div"),
          title = "Determinants of diversity (fixed effects models)",
          type = output_type)
```

