---
title: "Omnivorism: user-level analyses"
author: "Samuel Coavoux"
output: 
  html_document: 
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(message = FALSE,
               error = FALSE,
               echo = FALSE,
               warning = FALSE,
               results = 'asis',
               fig.path = "plot/")#,
               #dpi = 1200)
```

```{r packages}
library(tidyverse)
library(lubridate)
library(here)
library(forcats)
library(janitor)
library(stargazer)
library(lme4)
library(gridExtra)
library(texreg)
library(ggeffects)
# library(conflicted)
# conflict_prefer("filter", "dplyr")
# conflict_prefer("lag", "dplyr")
# conflict_prefer("grid.draw.ggplot", "ggplot2")
# conflict_prefer("plot.ggplot", "ggplot2")
# conflict_prefer("print.ggplot", "ggplot2")
```

```{r data}
load(here("data", "french_users.RData"))
# source(here("recodages", "herfindhal_diversity.R"))
# save(usd, file = here("data", "herfindhal.RData"))
load(here("data", "herfindhal.RData"))
source(here("recodages", "in_english.R"))
```

```{r misc_options}
if(isTRUE(getOption('knitr.in.progress'))) {
    output_type <- "html"#
} else {
    output_type <- "text"
}

theme_set(theme_bw(base_size = 12))

knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=" ")
})
options(scipen = 99)

```

We work on the usd database = users with exponential of shannon entropy See scripts for details about their computation.

We transform diversity: artists = log(artist).

```{r coding_logdiversity}
usd <- mutate(usd, across(starts_with("div_artists"), ~log(.x)))
#usd <- mutate(usd, across(starts_with("div_genre"), ~sqrt(.x)))
# Do not define stock/rec diversity when less than 100 data points
usd <- mutate(usd, across(.cols = matches("div_\\w+_stock"), ~ifelse(nb_stock < 100, NA, .x))) %>% 
  mutate(across(.cols = matches("div_\\w+_rec"), ~ifelse(nb_guid < 100, NA, .x)))

```

```{r coding_selectvariables}
usd <- select(usd, -ends_with("algo"), -ends_with("edit"))
```

# Personnes

```{r hist_us_age}
us <- mutate(us, age = ifelse(age > 90, NA, age))

ggplot(us, aes(age)) +
  geom_histogram()
```

# Diversity

```{r}
x <- select(usd, starts_with("richness"), div_artists, div_genre, div_omni) %>% 
  pivot_longer(everything()) %>% 
  mutate(Level = str_extract(name, "genre|artists|omni"),
         Type = str_extract(name, "strict|10|50"),
         Type = ifelse(Type == "strict", "1", Type),
         Type = ifelse(is.na(Type), "Herfindhal", paste(Type, "Richness", sep = "-")),
         Type = factor(Type, levels = c("1-Richness", "10-Richness", "50-Richness", "Herfindhal")),
         value = ifelse(Level == "artists" & Type != "Herfindhal", log(value), value))

```


```{r, fig.cap = "Artist diversity, richness vs. Herfindhal"}
filter(x, Level == "artists") %>% 
  ggplot(aes(value)) +
    geom_histogram() +
    labs(x = "Diversity", y = "Count") +
    facet_wrap(~Type, scales = "free_y", ncol = 2)

```

```{r, fig.cap = "Genre diversity, richness vs. Herfindhal"}
filter(x, Level == "genre") %>% 
  ggplot(aes(value)) +
    geom_histogram(binwidth = 0.5) +
    labs(x = "Diversity", y = "Count") +
    facet_wrap(~Type, scales = "free_y", ncol = 2)

```

```{r, fig.cap = "Legitimacy diversity, richness vs. Herfindhal"}
filter(x, Level == "omni") %>% 
  ggplot(aes(value)) +
    geom_histogram(binwidth = 0.1) +
    labs(x = "Diversity", y = "Count") +
    facet_wrap(~Type, scales = "free_y", ncol = 2)
```

```{r}
x <- select(usd, starts_with("richness"), div_artists, div_genre, div_omni, user_id) %>% 
  pivot_longer(-user_id) %>% 
  mutate(Level = str_extract(name, "genre|artists|omni"),
         Type = str_extract(name, "strict|10|50"),
         Type = ifelse(Type == "strict", "1", Type),
         Type = ifelse(is.na(Type), "Herfindhal", paste(Type, "Richness", sep = "-")),
         Type = factor(Type, levels = c("1-Richness", "10-Richness", "50-Richness", "Herfindhal")),
         value = ifelse(Level == "artists" & Type != "Herfindhal", log(value), value))

```

```{r}
ggplot(usd, aes(factor(richness_genre_strict), div_genre)) +
  geom_boxplot()
  geom_density_2d_filled()
```

```{r}
ggplot(usd, aes(factor(richness_omni_strict), div_omni)) +
  geom_boxplot()
 # geom_density_2d_filled()
```


```{r}
GGally::ggpairs(select(usd, starts_with("richness_artists"), div_artists))
```

```{r}
GGally::ggpairs(select(usd, starts_with("richness_genre"), div_genre))
```

```{r}
GGally::ggpairs(select(usd, starts_with("richness_omni"), div_omni))
```



```{r}
tabyl(usd, richness_omni_strict) %>% 
  adorn_pct_formatting() %>% 
  kable()
```

```{r}
tabyl(usd, richness_omni_50) %>% 
  adorn_pct_formatting() %>% 
  kable()
```


```{r hist_raw_diversity, fig.cap="Raw diversity"}
select(usd, starts_with("div_")) %>% pivot_longer(everything(), names_to = "names", values_to = "values") %>% 
  mutate(names = factor(names, levels = c("div_artists", "div_artists_rec", "div_artists_stock",
                                          "div_genre", "div_genre_rec", "div_genre_stock",
                                          "div_omni", "div_omni_rec", "div_omni_stock"),
                        labels = c("Artist diversity", "Artist div. rec.", "Artist div. stock",
                                          "Genre diversity", "Genre div. rec.", "Genre div. stock",
                                          "Omnivorism", "Omni. rec.", "Omni. stock"))) %>% 
  ggplot(aes(values)) +
    geom_histogram() +
    labs(x = "Diversity", y = "") +
    facet_wrap(~names, scales = "free", ncol = 3)
```

```{r}
GGally::ggpairs(select(usd, div_artists, div_genre, div_omni))
```

```{r}
GGally::ggpairs(select(usd, div_artists_stock, div_artists_rec, 
                       div_genre_stock, div_genre_rec, 
                       div_omni_stock, div_omni_rec))
```

# Recommended and stock diversity

```{r density_recstock, fig.cap="Density comparison of recommended and stock plays"}
select(usd, starts_with("div_"), -div_artists, -div_genre, -div_omni) %>%
  pivot_longer(everything(), names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "div_")) %>% 
  separate(names, into = c("type", "guid"), sep = "_") %>% 
  ggplot(aes(values, fill = guid)) +
    geom_density(alpha = 0.5) +
    facet_wrap(~type, scales = "free")
```

```{r scatter_recstock_diversity, fig.cap="Comparison between stock and recommended diversity on a user basis"}
select(usd, user_id, starts_with("div_"), -div_artists, -div_genre, -div_omni) %>%
  pivot_longer(-user_id, names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "div_")) %>% 
  separate(names, into = c("type", "guid"), sep = "_") %>% 
  pivot_wider(names_from = guid, values_from = values) %>% 
  ggplot(aes(rec, stock)) +
    geom_point() +
    facet_wrap(~type, scales = "free", ncol = 2) +
    geom_abline(slope = 1, intercept = 0, color = "red")
```

```{r , fig.cap = "Mean stock and recommended diversity"}
select(usd, user_id, starts_with("div_"), -div_artists, -div_genre, -div_omni) %>%
  pivot_longer(-user_id, names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "div_")) %>% 
  separate(names, into = c("type", "guid"), sep = "_") %>% 
  mutate(guid = factor(guid, levels = c("stock", "rec"))) %>% 
  group_by(type, guid) %>% 
  summarise(mean = mean(values, na.rm = TRUE),
            se = sd(values, na.rm = TRUE)/sqrt(n())) %>% 
  mutate(type = factor(type, levels = c("artists", "genre", "omni"),
                       labels = c("Artist div.", "Genre div.", "Omnivorism")),
         guid = factor(guid, levels = c("stock", "rec"),
                       labels = c("Stock", "Recommendations"))) %>% 
  ggplot(aes(guid, mean)) +
    geom_point() +
    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .2) +
    labs(x = "Context", "Mean diversity") +
    facet_wrap(~type)
```

```{r, fig.cap = "Mean stock and recommended diversity, per user"}
select(usd, user_id, starts_with("div_"), -div_artists, -div_genre, -div_omni) %>%
  pivot_longer(-user_id, names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "div_")) %>% 
  separate(names, into = c("type", "guid"), sep = "_") %>% 
  mutate(guid = factor(guid, levels = c("stock", "rec"), 
                       labels = c("Stock", "Recommendations")),
         type = factor(type, levels = c("artists", "genre", "omni"), 
                       labels = c("Artist div.", "Genre. div", "Omnivorism"))) %>% 
  ggplot(aes(guid, values)) +
    geom_boxplot(notch = TRUE) +
    #geom_point() +
    labs(x = "Contexts", y = "") +
    facet_wrap(~type, scales = "free")
```


```{r, fig.cap = "Mean stock and recommended diversity, per user"}
select(usd, user_id, starts_with("div_"), -div_artists, -div_genre, -div_omni) %>%
  pivot_longer(-user_id, names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "div_")) %>% 
  separate(names, into = c("type", "guid"), sep = "_") %>% 
  mutate(guid = factor(guid, levels = c("stock", "rec"), 
                       labels = c("Stock", "Recommendations")),
         type = factor(type, levels = c("artists", "genre", "omni"), 
                       labels = c("Artist div.", "Genre. div", "Omnivorism"))) %>% 
  ggplot(aes(guid, values)) +
    geom_boxplot(notch = TRUE) +
    geom_line(aes(group = user_id), ~ filter(.x, user_id %in% sample(.x$user_id, 10))) +
    labs(x = "Contexts", y = "") +
    #geom_point() +
    facet_wrap(~type, scales = "free")
```

```{r}
select(usd, user_id, starts_with("div_"), -div_artists, -div_genre, -div_omni, nb_stock, nb_guid) %>% 
  pivot_longer(starts_with("div_"), names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "div_")) %>% 
  separate(names, into = c("type", "guid"), sep = "_") %>% 
  mutate(nb = ifelse(guid == "rec", nb_guid, nb_stock),
         nb = log(nb)) %>% 
  mutate(guid = factor(guid, levels = c("stock", "rec"), 
                       labels = c("Stock", "Recommendations")),
         type = factor(type, levels = c("artists", "genre", "omni"), 
                       labels = c("Artist div.", "Genre. div", "Omnivorism"))) %>% 
  ggplot(aes(values, nb, color = guid)) +
    geom_point(size = .5) + 
    labs(x = "Diversity", y = "Log nb. of play", color = "Contexts") +
    facet_wrap(~type, scales = "free", ncol = 2) +
    theme(legend.position = c(1, 0),
          legend.justification = c(1, 0))
```

# Use of recommandations

```{r freq_us_activite}
tabyl(dat = us, var1 = passifs, var2 = gender) %>% 
  select(-NA_) %>% 
  adorn_percentages() %>% 
  adorn_pct_formatting() %>% 
  kable(caption="Activity and gender")
```

# Omnivorism

```{r reco_density, fig.cap = "Distribution of frequency of use of recommendation"}
ggplot(us, aes(fq)) +
  geom_line(stat="density") +
  labs(y = "Density", x = "Use frequency of recommendations")
```

```{r reco_hist, fig.cap = "Distribution of frequency of use of recommendation"}
ggplot(us, aes(fq)) +
  geom_histogram() +
  labs(y = "", x = "Use frequency of recommendations")
```

## Link with use of algo

```{r diversity_X_dip_profile_table}
filter(usd, !is.na(passifs)) %>%
  group_by(passifs) %>%
  summarize(`Mean log (artists) diversity (sd)` = paste0(round(mean(div_artists), 1), " (", round(sd(div_artists), 1), ")"),
            `Mean (genres) diversity (sd)` = paste0(round(mean(div_genre), 1), " (", round(sd(div_genre), 1), ")"),
            `Mean (omnivore) diversity (sd)` = paste0(round(mean(div_omni, na.rm = TRUE), 1), " (", round(sd(div_omni, na.rm = TRUE), 1), ")")) %>%
  rename(` ` = passifs) %>%
  kable(caption = "Diversity by listener profile")
```

```{r}
filter(usd, !is.na(passifs)) %>% 
  select(passifs, div_artists, div_genre, div_omni) %>% 
  pivot_longer(-passifs) %>% 
    mutate(name = factor(name, levels = c("div_artists", "div_genre", "div_omni"), 
                       labels = c("Artist div.", "Genre. div", "Omnivorism"))) %>% 
  ggplot(aes(value, fill = passifs)) +
    geom_density(alpha = .5) +
    facet_wrap(~name, ncol = 2, scales = "free") +
    labs(x = "Diversity", y = "Density", color = "Diversity", fill = "") +
    theme(legend.position = c(1, 0),
          legend.justification = c(1, 0))

```

```{r}
filter(usd, !is.na(passifs)) %>% 
  ggplot(aes(div_genre, fill = passifs)) +
    geom_density(alpha = .5)
```

```{r}
filter(usd, !is.na(passifs)) %>% 
  ggplot(aes(div_omni, fill = passifs)) +
    geom_density(alpha = .5)
```

# OLS model

```{r diversity_lm_table}
daflm <- lm(div_artists ~ I(fq*10), data = us)
danlm <- lm(div_artists ~ log(nb_ecoutes), data = us)
dalm  <- lm(div_artists ~ I(fq*10) + age + gender + I(freq_nouveaute*10) + log(nb_ecoutes), data = us)

dgflm <- lm(div_genre   ~ I(fq*10), data = us)
dgnlm <- lm(div_genre   ~ log(nb_ecoutes), data = us)
dglm  <- lm(div_genre   ~ I(fq*10) + age + gender + I(freq_nouveaute*10) + log(nb_ecoutes), data = us)

doflm <- lm(div_omni   ~ I(fq*10), data = us)
donlm <- lm(div_omni   ~ log(nb_ecoutes), data = us)
dolm  <- lm(div_omni   ~ I(fq*10) + age + gender + I(freq_nouveaute*10) + log(nb_ecoutes), data = us)

htmlreg(list(daflm, dalm,
            dgflm, dglm,
            doflm, dolm),
       custom.coef.names = c("Intercept",
                             "Freq. rec. (10pp)",
                             "Age (in years)",
                             "Gender - Male",
                             "Freq. novelty (10pp)",
                             "Log nb of tracks"),
       custom.model.names = c("Art. div.", "Art div.", "Genre div.", "Genre div.", "Omni.", "Omni."))


```

```{r}
dalm  <- lm(div_artists ~ I(fa*10) + I(fe*10) + age + gender + I(freq_nouveaute*10) + log(nb_ecoutes), data = us)
dglm  <- lm(div_genre   ~ I(fa*10) + I(fe*10) + age + gender + I(freq_nouveaute*10) + log(nb_ecoutes), data = us)
dolm  <- lm(div_omni    ~ I(fa*10) + I(fe*10) + age + gender + I(freq_nouveaute*10) + log(nb_ecoutes), data = us)

htmlreg(list(dalm, dglm, dolm),
       custom.coef.names = c("Intercept",
                             "Freq. algo. (10pp)",
                             "Freq. edit. (10pp)",
                             "Age (in years)",
                             "Gender - Male",
                             "Freq. novelty (10pp)",
                             "Log nb of tracks"),
       custom.model.names = c("Art. div.", "Genre div.", "Omni."))


```

# Fixed effects models

```{r}
# Three solutions; results not very different. I prefer the first one, more explicit
usd_lm <- filter(usd, nb_guid > 100, nb_stock > 100, across(.cols = starts_with("div_"), .fns = ~ !is.na(.x)))
#usd_lm <- usd
```



```{r}
x <- select(usd_lm, user_id, div_artists_rec, div_artists_stock, nb_guid, nb_stock, fq, freq_nouveaute, gender, age)
x <- pivot_longer(x, cols = starts_with("div_artists")) %>% 
  mutate(name = str_extract(name, "(rec|stock)$") %>% factor(levels = c("stock", "rec")), 
         nb = ifelse(name == "rec", nb_guid, nb_stock)) %>% 
  select(-nb_guid, -nb_stock) %>% 
  group_by(user_id) %>% 
  filter(!any(is.na(value)))

x <- mutate(x, lognb = log(nb))

# Quels sont les niveaux?
fe_us_artdiv <- lmer(value ~ name + lognb + gender + ( 1 | user_id), data = x)
fe_us_artdiv_uncond <- lmer(value ~ 1 + ( 1 | user_id), data = x)
```

```{r}
x <- select(usd_lm, user_id, div_genre_rec, div_genre_stock, nb_guid, nb_stock, fq, freq_nouveaute, gender, age)
x <- pivot_longer(x, cols = starts_with("div_genre")) %>% 
  mutate(name = str_extract(name, "(rec|stock)$") %>% factor(levels = c("stock", "rec")), 
         nb = ifelse(name == "rec", nb_guid, nb_stock)) %>% 
  select(-nb_guid, -nb_stock) %>% 
  group_by(user_id) %>% 
  filter(!any(is.na(value)))

x <- mutate(x, lognb = log(nb))

# Quels sont les niveaux?
fe_us_genrediv <- lmer(value ~ name + lognb + gender + ( 1 | user_id), data = x)
fe_us_genrediv_uncond <- lmer(value ~ 1 + ( 1 | user_id), data = x)
```


```{r}
x <- select(usd_lm, user_id, div_omni_rec, div_omni_stock, nb_guid, nb_stock, fq, freq_nouveaute, gender, age)
x <- pivot_longer(x, cols = starts_with("div_omni")) %>% 
  mutate(name = str_extract(name, "(rec|stock)$") %>% factor(levels = c("stock", "rec")), 
         nb = ifelse(name == "rec", nb_guid, nb_stock)) %>% 
  select(-nb_guid, -nb_stock) %>% 
  group_by(user_id) %>% 
  filter(!any(is.na(value)))

x <- mutate(x, lognb = log(nb))

# Quels sont les niveaux?
fe_us_omnidiv <- lmer(value ~ name + lognb + gender + ( 1 | user_id), data = x)
fe_us_omnidiv_uncond <- lmer(value ~ 1 + ( 1 | user_id), data = x)
```

## Unconditional models

```{r}
library(sjstats)
library(sjPlot)

tab_model(fe_us_artdiv_uncond, fe_us_genrediv_uncond, fe_us_omnidiv_uncond)
```

## MLM

```{r}
fe_us <- list(fe_us_artdiv, fe_us_genrediv, fe_us_omnidiv)

htmlreg(fe_us,
        custom.model.names = c("Artists div.", "Genre div.", "Omnivorism"),
        custom.coef.names = c("Intercept", "Contexts: rec.", "Log nb. plays", "Gender: Male"))
```

```{r}
tab_model(fe_us_artdiv, fe_us_genrediv, fe_us_omnidiv, p.val = "kr")
```

```{r}
sd(usd_lm$div_artists)
sd(usd_lm$div_genre)
sd(usd_lm$div_omni)
```


```{r}
plotreg(fe_us,
        custom.model.names = c("Artists div.", "Genre div.", "Omnivorism"),
        custom.coef.names = c("Intercept", "Contexts: rec.", "Log nb. plays", "Gender: Male"))
```

```{r}
x <- ranef(fe_us_artdiv)$user_id %>% 
  rownames_to_column("User") %>% 
  mutate(model = "Artists div.")
y <- ranef(fe_us_genrediv)$user_id %>% 
  rownames_to_column("User") %>% 
  mutate(model = "Genre div.")
z <- ranef(fe_us_omnidiv)$user_id %>% 
  rownames_to_column("User") %>% 
  mutate(model = "Omnivorism")
us_ranef <- bind_rows(x, y, z) %>% 
  rename(intercept = "(Intercept)") %>% 
  tibble()
```

```{r}
group_by(us_ranef, model) %>% 
  arrange(intercept) %>% 
  mutate(rank = row_number()) %>% 
  ggplot(aes(rank, intercept)) +
    geom_point() +
    geom_hline(yintercept = 0) +
    facet_wrap(~model) +
    labs(x = "", y = "User-level random effect")
```

```{r}
pivot_wider(us_ranef, names_from = "model", values_from = "intercept") %>% 
  select(-User) %>% 
  GGally::ggpairs()
```

```{r}
pivot_wider(us_ranef, names_from = model, values_from = intercept) %>% 
  ggplot(aes(`Artists div.`, `Genre div.`)) +
    geom_point() +
    labs(x = "User level random effect - Artists div.",
         y = "User level random effect - Genre div.")
```


```{r}
pivot_wider(us_ranef, names_from = model, values_from = intercept) %>% 
  ggplot(aes(`Artists div.`, `Omnivorism`)) +
    geom_point() +
    labs(x = "User level random effect - Artists div.",
         y = "User level random effect - Omnivorism")

```

```{r}
pivot_wider(us_ranef, names_from = model, values_from = intercept) %>% 
  ggplot(aes(`Genre div.`, `Omnivorism`)) +
    geom_point() +
    labs(x = "User level random effect - Genre div.",
         y = "User level random effect - Omnivorism")

```

```{r, eval = FALSE}
ggpredict(fe_us_artdiv, c("lognb", "name"), type="random") %>%
  ggplot(aes(x, predicted, colour = group)) +
    stat_smooth(method = "lm", se = FALSE)

```

```{r, eval = FALSE}
ggpredict(fe_us_genrediv, c("lognb", "name"), type="random") %>%
  ggplot(aes(x, predicted, colour = group)) +
    stat_smooth(method = "lm", se = FALSE)

```

```{r, eval = FALSE}
ggpredict(fe_us_omnidiv, c("lognb", "name"), type="random") %>%
  ggplot(aes(x, predicted, colour = group)) +
    stat_smooth(method = "lm", se = FALSE)

```

# Omnivorism

```{r}
count(usd, Highbrow > 0.1 & Lowbrow > 0.1 & Middlebrow > 0.1)
```

